apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260511-004719-k880bv07r1s0-service
spec:
  selector:
    app: enterprise-system-20260511-004719-k880bv07r1s0
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
